[theme]
primaryColor = "#006400"               # Verde oscuro para los títulos y acentos
backgroundColor = "#FFFFFF"            # Fondo completamente blanco
secondaryBackgroundColor = "#90EE90"   # Verde claro para secciones secundarias (subtítulos)
textColor = "#006400"                  # Verde oscuro para texto general
font = "sans serif"                    # Tipografía sans serif para todo el texto
