[theme]
primaryColor = "#66CDAA"               # Verde medio claro para elementos principales
backgroundColor = "#F5FFFA"            # Casi blanco con un leve tinte verde
secondaryBackgroundColor = "#E0F8E0"   # Verde muy suave para secciones secundarias
textColor = "#064635"                  # Verde oscuro para el texto
font = "monospace"
